// AUTO-GENERATED by font-lab/generate.mjs — 直接編集しない。
// round 5 / 12 combos
import type { FontPairing } from './font-catalog';

export const generatedRound = 5;

export const fontPairings: readonly FontPairing[] = [
  { no: 1, id: "MochiyPopPOne_400Regular__NotoSansJP_400Regular", name: "Mochiy Pop P One × Noto Sans JP", display: "MochiyPopPOne_400Regular", body: "NotoSansJP_400Regular", bodyBold: "NotoSansJP_700Bold", kind: "anchor" },
  { no: 2, id: "DelaGothicOne_400Regular__MPLUSRounded1c_400Regular", name: "Dela Gothic One × M PLUS Rounded 1c", display: "DelaGothicOne_400Regular", body: "MPLUSRounded1c_400Regular", bodyBold: "MPLUSRounded1c_700Bold", kind: "anchor" },
  { no: 3, id: "ReggaeOne_400Regular__MPLUSRounded1c_400Regular", name: "Reggae One × M PLUS Rounded 1c", display: "ReggaeOne_400Regular", body: "MPLUSRounded1c_400Regular", bodyBold: "MPLUSRounded1c_700Bold", kind: "learned" },
  { no: 4, id: "ReggaeOne_400Regular__NotoSansJP_400Regular", name: "Reggae One × Noto Sans JP", display: "ReggaeOne_400Regular", body: "NotoSansJP_400Regular", bodyBold: "NotoSansJP_700Bold", kind: "learned" },
  { no: 5, id: "DelaGothicOne_400Regular__MPLUS1_400Regular", name: "Dela Gothic One × M PLUS 1", display: "DelaGothicOne_400Regular", body: "MPLUS1_400Regular", bodyBold: "MPLUS1_700Bold", kind: "learned" },
  { no: 6, id: "MochiyPopPOne_400Regular__MPLUS1_400Regular", name: "Mochiy Pop P One × M PLUS 1", display: "MochiyPopPOne_400Regular", body: "MPLUS1_400Regular", bodyBold: "MPLUS1_700Bold", kind: "learned" },
  { no: 7, id: "MochiyPopOne_400Regular__Murecho_400Regular", name: "Mochiy Pop One × Murecho", display: "MochiyPopOne_400Regular", body: "Murecho_400Regular", bodyBold: "Murecho_700Bold", kind: "learned" },
  { no: 8, id: "MochiyPopOne_400Regular__ZenMaruGothic_400Regular", name: "Mochiy Pop One × Zen Maru Gothic", display: "MochiyPopOne_400Regular", body: "ZenMaruGothic_400Regular", bodyBold: "ZenMaruGothic_700Bold", kind: "learned" },
  { no: 9, id: "HachiMaruPop_400Regular__ZenKakuGothicNew_400Regular", name: "Hachi Maru Pop × Zen Kaku Gothic New", display: "HachiMaruPop_400Regular", body: "ZenKakuGothicNew_400Regular", bodyBold: "ZenKakuGothicNew_700Bold", kind: "learned" },
  { no: 10, id: "Stick_400Regular__KleeOne_400Regular", name: "Stick × Klee One", display: "Stick_400Regular", body: "KleeOne_400Regular", bodyBold: "KleeOne_600SemiBold", kind: "random" },
  { no: 11, id: "RampartOne_400Regular__Murecho_400Regular", name: "Rampart One × Murecho", display: "RampartOne_400Regular", body: "Murecho_400Regular", bodyBold: "Murecho_700Bold", kind: "random" },
  { no: 12, id: "HachiMaruPop_400Regular__ZenMaruGothic_400Regular", name: "Hachi Maru Pop × Zen Maru Gothic", display: "HachiMaruPop_400Regular", body: "ZenMaruGothic_400Regular", bodyBold: "ZenMaruGothic_700Bold", kind: "random" },
];
